/**
 * What art exists, and where it lives.
 *
 * The manifest is generated by `scripts/art-build.js` from whatever is in the
 * `art/` folder, so this module is the single place that knows whether a given
 * id has a picture. Everything else asks rather than assumes — an id with no
 * file falls back to the generated placeholder, which is what lets art arrive a
 * few pieces at a time without anything breaking.
 */

import manifest from '@/data/artManifest.json';
import { ESSENCES } from '@/sim/types';
import type { Essence, EssenceVector } from '@/sim/types';

/**
 * The essence a blend leans hardest on.
 *
 * Lives here rather than beside the Phaser placeholder code because the DOM
 * panels need it too, and importing that module would pull the whole engine
 * into the panel bundle for one pure function.
 */
export function dominantEssence(vector: EssenceVector): Essence {
  let best: Essence = 'terra';
  let value = -1;
  for (const essence of ESSENCES) {
    if (vector[essence] > value) {
      value = vector[essence];
      best = essence;
    }
  }
  return best;
}

export type ArtKind = 'ingredient' | 'decor' | 'potion' | 'scene' | 'shelf' | 'merchant' | 'hero';

const sets: Record<ArtKind, Set<string>> = {
  ingredient: new Set(manifest.ingredient ?? []),
  decor: new Set(manifest.decor ?? []),
  potion: new Set(manifest.potion ?? []),
  scene: new Set(manifest.scene ?? []),
  shelf: new Set(manifest.shelf ?? []),
  merchant: new Set(manifest.merchant ?? []),
  hero: new Set(manifest.hero ?? []),
};

export function hasArt(kind: ArtKind, id: string): boolean {
  return sets[kind].has(id);
}

/**
 * Relative on purpose: the build sets `base: './'` so the same path resolves
 * from a web root, a subdirectory, and a Capacitor WebView's file:// origin.
 *
 * WebP, at twice the size anything is drawn — `scripts/art-build.js` says why.
 */
export function artUrl(kind: ArtKind, id: string): string {
  return `art/${kind}/${id}.webp`;
}

/** The url, or null when there is no art — callers decide what to draw instead. */
export function artUrlIf(kind: ArtKind, id: string): string | null {
  return hasArt(kind, id) ? artUrl(kind, id) : null;
}

export function idsWithArt(kind: ArtKind): string[] {
  return [...sets[kind]];
}
